name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
         python -m pytest tests/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v1

    - name: Configure kubectl
      run: |
        kubectl config set-cluster my-cluster --server=<CLUSTER_ENDPOINT> --certificate-authority=<CA_CERT>
        kubectl config set-credentials my-user --token=<USER_TOKEN>
        kubectl config set-context my-context --cluster=my-cluster --user=my-user
        kubectl config use-context my-context
      env:
        CLUSTER_ENDPOINT: ${{ secrets.CLUSTER_ENDPOINT }}
        CA_CERT: ${{ secrets.CA_CERT }}
        USER_TOKEN: ${{ secrets.USER_TOKEN }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Verify cluster access
      run: |
        kubectl get nodes
